name: Testing taskiq-aio-sqs

on:
  pull_request:
      branches:
          - main
          - develop

jobs:
  lint:
    strategy:
      matrix:
        cmd:
          - ruff
          - pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install --upgrade pip
          make install
      - name: Run lint check
        run: python3 -m pre_commit run -a ${{ matrix.cmd }}
  pytest:
    strategy:
      matrix:
        py-version: ["3.10", "3.11", "3.12"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.py_version }}"
      - name: Install deps
        run: |
          pip install --upgrade pip
          make install py_version="${{ matrix.py_version }}"
      - name: Run pytest check
        run: make test py_version=${{ matrix.py_version }}
      - name: Show Coverage
        if: github.event_name == 'pull_request' && matrix.py_version == '3.10'
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: coverage.xml
            thresholdAll: 0.90
            thresholdNew: 0.95
            token: ${{ secrets.GITHUB_TOKEN }}
